export const DATA = {
  name: "Alex Moreau",
  title: "Développeur Full-Stack",
  tagline: "Je construis des expériences\nnumériques qui ont du sens.",
  about:
    "Passionné par l'intersection du code et du design, je crée des applications web soignées avec une attention particulière à l'expérience utilisateur. Chaque projet est une opportunité de repousser les limites techniques tout en gardant l'humain au centre.",
  email: "alex.moreau@dev.fr",
  github: "github.com/alexmoreau",
  linkedin: "linkedin.com/in/alexmoreau",
  location: "Paris, France",
  availability: "Disponible — Freelance / CDI",

  stats: [
    { value: "3+", label: "Années d'expérience" },
    { value: "24", label: "Projets livrés" },
    { value: "12", label: "Clients satisfaits" },
    { value: "99", label: "Score Lighthouse" },
  ],

  skills: [
    {
      cat: "Front-end",
      icon: "◈",
      items: ["React", "TypeScript", "Next.js", "Tailwind CSS", "Three.js", "Framer Motion"],
    },
    {
      cat: "Back-end",
      icon: "◉",
      items: ["Node.js", "Python", "PostgreSQL", "REST API", "GraphQL", "Redis"],
    },
    {
      cat: "Outils & DevOps",
      icon: "◐",
      items: ["Git", "Docker", "Figma", "Vercel", "AWS", "CI/CD"],
    },
  ],

  timeline: [
    {
      year: "2024",
      role: "Développeur Senior",
      place: "Agence Pixel · Paris",
      desc: "Lead front-end sur 8 projets clients. Migration vers Next.js 14, mise en place d'un design system partagé.",
      type: "work",
    },
    {
      year: "2022",
      role: "Développeur Full-Stack",
      place: "StartupX · Lyon",
      desc: "Construction du MVP de A à Z. Stack React + FastAPI + PostgreSQL. Levée de fonds série A réussie.",
      type: "work",
    },
    {
      year: "2021",
      role: "Master Informatique",
      place: "Université Paris-Saclay",
      desc: "Spécialisation génie logiciel et systèmes distribués. Major de promotion.",
      type: "edu",
    },
    {
      year: "2019",
      role: "Licence Informatique",
      place: "IUT de Grenoble",
      desc: "Bases solides en algorithmique, POO et bases de données relationnelles.",
      type: "edu",
    },
  ],

  projects: [
    {
      id: 1,
      cat: "Web App",
      title: "Palette Studio",
      desc: "Outil de génération de palettes avec IA. Export vers Figma, CSS et Tailwind en un clic.",
      tech: ["React", "OpenAI API", "Node.js"],
      year: "2024",
      featured: true,
      color: "#00d4ff",
    },
    {
      id: 2,
      cat: "E-commerce",
      title: "Maison Blanche",
      desc: "Boutique haut de gamme pour une marque de mobilier. SSR, SEO optimisé, score Lighthouse 99.",
      tech: ["Next.js", "Stripe", "Sanity CMS"],
      year: "2024",
      featured: true,
      color: "#a78bfa",
    },
    {
      id: 3,
      cat: "Dashboard",
      title: "AnalytiX",
      desc: "Dashboard temps réel pour équipes marketing. Visualisation de données et exports PDF automatisés.",
      tech: ["React", "D3.js", "FastAPI", "PostgreSQL"],
      year: "2023",
      featured: false,
      color: "#34d399",
    },
    {
      id: 4,
      cat: "Mobile",
      title: "TrailMate",
      desc: "Application de randonnée avec cartes offline, suivi GPS et partage de parcours communautaire.",
      tech: ["React Native", "Mapbox", "SQLite"],
      year: "2023",
      featured: false,
      color: "#fb923c",
    },
    {
      id: 5,
      cat: "Web App",
      title: "CodeReview AI",
      desc: "Assistant de code review automatisé intégré à GitHub. Détecte les bugs, suggère des refactorisations.",
      tech: ["Python", "GitHub API", "GPT-4"],
      year: "2022",
      featured: true,
      color: "#f472b6",
    },
    {
      id: 6,
      cat: "Dashboard",
      title: "EcoTrack",
      desc: "Suivi de l'empreinte carbone d'une entreprise avec rapports mensuels et objectifs RSE.",
      tech: ["Vue.js", "Chart.js", "Django"],
      year: "2022",
      featured: false,
      color: "#4ade80",
    },
  ],
};
